### 服务器配置
server:
    port: 80
    tomcat.uri-encoding: UTF-8
###  context-path: /vcoinb

### mybatis配置
mybatis:
    type-aliases-package: lzlz.boardgame.dao.entity
    mapper-locations: classpath:mapper/*.xml

mapper:
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

### spring配置
spring:
    ###禁用默认favicon
    mvc.favicon.enabled: false
    http:
        encoding.charset: UTF-8
        encoding.force: true
    ##模板引擎
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        content-type: text/html
        mode: HTML
    ##redis
    redis:
        database: 1
        host: localhost
        port: 6379
        password: QWERDF595182653QWERDF595182653
    ##数据库连接
    datasource:
        url: jdbc:mysql://localhost:3306/test?useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;allowMultiQueries=true
        username: vcoin
        password: QWERDF595182653
        driver-class-name: com.mysql.jdbc.Driver
###日志
logging:
    file: ./logs/spring-boot-logging.log
    level:
        root: info
        lzlz.boardgame.socket.*: warn